(() => {
  'use strict';
  const make=(tag,text='',cls='')=>{const n=document.createElement(tag);n.textContent=text;n.className=cls;return n;};
  const action=(text,fn)=>{const b=make('button',text,'vr-button');b.type='button';b.onclick=fn;return b;};
  const style=make('style');style.textContent=`
  dialog.ov-publish{box-sizing:border-box!important;width:min(760px,calc(100% - 24px))!important;max-height:calc(100dvh - 24px)!important;padding:24px!important;border-radius:18px;font:16px/1.5 'Segoe UI',sans-serif;color:#253047;background:white;overflow:auto}
  .ov-publish header{display:flex;justify-content:space-between;align-items:center;gap:16px}.ov-publish h2{font-size:23px;margin:0}.ov-publish h3{font-size:18px;margin:0 0 14px}.ov-publish p{margin:10px 0}.ov-publish .ov-pub-steps{display:flex;gap:8px;list-style:none;padding:0;margin:20px 0}.ov-pub-steps li{flex:1;text-align:center;background:#f2f4f8;border-radius:10px;padding:10px 5px;font-size:13px}.ov-pub-steps li[aria-current]{background:#eee7ff;color:#6339a6;font-weight:600}
  .ov-pub-panel{border:1px solid #e1e5ed;border-radius:14px;padding:18px}.ov-publish label{display:grid;gap:8px;margin:12px 0}.ov-publish .ov-pub-account,.ov-publish .ov-pub-consent{display:flex;align-items:flex-start;gap:12px}.ov-publish input[type=checkbox]{width:20px;height:20px;flex-shrink:0;accent-color:#7647d4}.ov-publish select,.ov-publish textarea,.ov-publish input[type=datetime-local]{box-sizing:border-box;width:100%;padding:12px;border:1px solid #bac4d2;border-radius:9px;font:inherit;color:inherit;background:white}.ov-publish textarea{resize:vertical}.ov-publish video,.ov-publish img{display:block;width:100%!important;height:min(32dvh,280px)!important;object-fit:contain!important;border-radius:10px;background:#101827}.ov-publish footer{position:sticky;bottom:0;display:flex;justify-content:flex-end;gap:12px;padding:16px 0 0;background:white;z-index:2}.ov-publish footer button{min-height:46px;padding:12px 18px!important;border-radius:10px!important}.ov-publish .ov-pub-primary{background:#7647d4!important;color:white!important;border-color:#7647d4!important}.ov-publish button:disabled{opacity:.6;cursor:default}.ov-publish [hidden]{display:none!important}.ov-pub-note{color:#58677f;font-size:14px}.ov-pub-error{color:#a12739}.ov-pub-result{margin:12px 0;padding:14px;border:1px solid #e1e5ed;border-radius:12px;background:#f5f3ff}.ov-pub-result[data-state=published],.ov-pub-result[data-state=inbox]{background:#effaf3;border-color:#b8ddc5}.ov-pub-result[data-state=failed],.ov-pub-result[data-state=uncertain]{background:#fff6eb;border-color:#e7c9a0}
  @media(max-width:480px){dialog.ov-publish{padding:16px!important}.ov-publish h2{font-size:19px}.ov-pub-steps li{font-size:11px}.ov-pub-panel{padding:12px}.ov-publish footer{flex-wrap:wrap}.ov-publish footer button{flex:1}}
  `;document.head.append(style);
  const headers={'Content-Type':'application/json','X-Olyvex-Request':'1'};
  async function api(network,path,options={}){const r=await fetch('/api/social/'+network+'/'+path,{credentials:'same-origin',...options});let data;try{data=await r.json();}catch{throw Error('Réponse du serveur indisponible.');}if(!r.ok)throw Error(data.error||'Opération indisponible.');return data;}
  const names={facebook:'Facebook',instagram:'Instagram',tiktok:'TikTok'};
  const labels={queued:'En attente d’envoi',processing:'Traitement en cours',uploading:'Transfert vers TikTok',waiting:'Préparation par le réseau',published:'Publication confirmée',inbox:'Brouillon reçu par TikTok',failed:'Échec de l’envoi',uncertain:'Résultat à vérifier',cancelled:'Publication annulée'};
  window.olyvexSocialComposer=async campaign=>{
    const d=make('dialog','','vr-lightbox ov-social-dialog ov-publish');d.setAttribute('aria-label','Publication sur vos réseaux');const form=make('form');const head=make('header');head.append(make('h2','Publier sur vos réseaux'),action('Fermer',()=>d.close()));form.append(head,make('p','Préparez votre contenu et suivez chaque destination, étape par étape.','ov-pub-note'));const message=make('p','Chargement des comptes…');message.setAttribute('role','status');form.append(message);d.append(form);document.body.append(d);let timer,sending=false;d.addEventListener('close',()=>{clearInterval(timer);d.remove();},{once:true});d.showModal();
    const results=await Promise.allSettled([api('meta','accounts'),api('tiktok','accounts')]);if(!d.isConnected)return;
    const accounts=[];results.forEach((r,i)=>{if(r.status==='fulfilled')for(const a of r.value.accounts||[])accounts.push({...a,network:i?'tiktok':'meta',platform:i?'tiktok':a.platform});});
    const notices=results.map((r,i)=>r.status==='rejected'?(i?'TikTok':'Facebook et Instagram')+' : '+r.reason.message:'').filter(Boolean);
    message.textContent=notices.join(' · ');if(!accounts.length){message.textContent='Connectez vos comptes dans Paramètres → Mes réseaux avant de publier.';return;}
    const steps=make('ol','','ov-pub-steps');const titles=['Réseaux','Contenu','Confirmation','Suivi'];const stepItems=titles.map((name,i)=>{const n=make('li',(i+1)+'. '+name);steps.append(n);return n;});form.append(steps);
    const panels=titles.map((name,i)=>{const n=make('section','','ov-pub-panel');const h=make('h3',(i+1)+'. '+name);h.tabIndex=-1;n.append(h);form.append(n);return n;});
    const fields=[];for(const a of accounts){const l=make('label','','ov-pub-account');const c=make('input');c.type='checkbox';const text=make('span',names[a.platform]+' · '+a.display_name);l.append(c,text);panels[0].append(l);fields.push({a,c});}
    panels[0].append(make('p','Facebook et Instagram : publication directe ou programmée. TikTok : brouillon à terminer sur votre téléphone.','ov-pub-note'));
    const data=campaign.campaign_data||{},media=make('select');const choices=[];if(data.videoUrl)choices.push(['video','Vidéo finale']);(data.generatedImages||[]).forEach((src,i)=>{if(/^data:image\/(png|jpeg|webp);base64,/i.test(src))choices.push(['image:'+i,'Image '+(i+1)]);});choices.push(['text','Texte uniquement · Facebook']);for(const [value,text] of choices){const o=make('option',text);o.value=value;media.append(o);}
    const field=(parent,title,input)=>{const l=make('label');l.append(make('span',title),input);parent.append(l);return l;};field(panels[1],'Contenu',media);const previewBox=make('div');panels[1].append(previewBox);
    const caption=make('textarea');caption.rows=4;caption.maxLength=2200;field(panels[1],'Texte de publication',caption);const tags=make('textarea');tags.rows=2;field(panels[1],'Hashtags',tags);const captionNote=make('p','','ov-pub-note');panels[1].append(captionNote);
    const when=make('select');for(const [value,text] of [['now','Maintenant'],['later','Programmer Facebook et Instagram']]){const o=make('option',text);o.value=value;when.append(o);}const whenField=field(panels[1],'Quand publier ?',when);const date=make('input');date.type='datetime-local';const dateField=field(panels[1],'Date et heure locales',date);dateField.hidden=true;when.onchange=()=>{dateField.hidden=when.value!=='later';};
    const recap=make('div');panels[2].append(recap);const agree=make('input');agree.type='checkbox';const consent=make('label','','ov-pub-consent');consent.append(agree,make('span','J’ai vérifié le contenu et les comptes. J’autorise la publication Facebook / Instagram et l’envoi du brouillon TikTok sélectionnés.'));panels[2].append(consent);
    const statusList=make('div');statusList.setAttribute('aria-live','polite');panels[3].append(statusList,make('p','Vous pouvez fermer cette fenêtre et retrouver les résultats dans Paramètres → Mes réseaux.','ov-pub-note'));
    const foot=make('footer');const back=action('Retour',()=>go(step-1));const next=action('Continuer',()=>advance());next.classList.add('ov-pub-primary');const send=make('button','Confirmer et envoyer','vr-button ov-pub-primary');send.type='submit';const done=action('Fermer',()=>d.close());foot.append(back,next,send,done);form.append(foot);let step=0;
    const selected=()=>fields.filter(x=>x.c.checked).map(x=>x.a);const text=()=>[caption.value.trim(),tags.value.trim()].filter(Boolean).join('\n\n');
    function go(i){step=i;panels.forEach((p,k)=>p.hidden=k!==i);stepItems.forEach((n,k)=>{if(k===i)n.setAttribute('aria-current','step');else n.removeAttribute('aria-current');});back.hidden=i===0||i===3;next.hidden=i>=2;send.hidden=i!==2;done.hidden=i!==3;panels[i].querySelector('h3').focus();}
    function preview(){previewBox.replaceChildren();const [kind,index]=media.value.split(':');if(kind==='video'){const u=new URL(data.videoUrl,location.origin);if(u.origin!==location.origin||!/^\/videos\/vira-[a-zA-Z0-9_-]+\.mp4$/.test(u.pathname)){message.textContent='Vidéo enregistrée indisponible.';return;}const v=make('video');v.src=u.href;v.controls=true;v.preload='metadata';v.setAttribute('playsinline','');previewBox.append(v);}else if(kind==='image'){const img=make('img');img.src=data.generatedImages[Number(index)];img.alt='Aperçu du contenu sélectionné';previewBox.append(img);}}
    media.onchange=()=>{agree.checked=false;preview();};caption.oninput=tags.oninput=()=>{agree.checked=false;};
    function validate(){const list=selected();if(!list.length)return 'Sélectionnez au moins un compte.';const kind=media.value.split(':')[0];if(kind==='video'){try{const u=new URL(data.videoUrl,location.origin);if(u.origin!==location.origin||!/^\/videos\/vira-[a-zA-Z0-9_-]+\.mp4$/.test(u.pathname))return 'Vidéo enregistrée indisponible.';}catch{return 'Vidéo enregistrée indisponible.';}}if(list.some(a=>a.platform==='tiktok')&&kind!=='video')return 'TikTok nécessite une vidéo finale. Choisissez une vidéo ou retirez TikTok.';if(list.some(a=>a.platform==='instagram')&&kind==='text')return 'Instagram nécessite une image ou une vidéo.';if(kind==='text'&&!text())return 'Ajoutez le texte de publication.';const limit=list.some(a=>a.platform==='instagram')?2200:5000;if(text().length>limit)return 'Le texte et les hashtags dépassent '+limit+' caractères.';if(when.value==='later'){if(list.some(a=>a.platform==='tiktok'))return 'La programmation concerne Facebook et Instagram. Retirez TikTok ou choisissez Maintenant.';if(!date.value||!Number.isFinite(new Date(date.value).getTime())||new Date(date.value)<=new Date())return 'Choisissez une date et une heure futures.';}return '';}
    function advance(){message.textContent='';if(step===0){if(!selected().length){message.textContent='Sélectionnez au moins un compte.';return;}whenField.hidden=selected().every(a=>a.platform==='tiktok');if(whenField.hidden){when.value='now';dateField.hidden=true;}captionNote.textContent=selected().some(a=>a.platform==='tiktok')?'Pour TikTok, copiez ce texte et collez-le lors de la publication sur votre téléphone. Il sera envoyé directement avec la publication Facebook / Instagram.':'Le texte et les hashtags seront envoyés avec votre publication.';preview();go(1);}else{const error=validate();if(error){message.textContent=error;return;}recap.replaceChildren();for(const a of selected())recap.append(make('p',names[a.platform]+' · '+a.display_name+' — '+(a.platform==='tiktok'?'brouillon à terminer sur téléphone':when.value==='later'?'publication le '+new Date(date.value).toLocaleString('fr-CA'):'publication immédiate')));recap.append(make('p',text()||'Sans texte de publication','ov-pub-note'));agree.checked=false;go(2);}}
    const jobs=[];function show(j,status,error=''){j.status=status;j.box.dataset.state=status;j.box.replaceChildren(make('strong',names[j.a.platform]+' · '+j.a.display_name),make('p',labels[status]||status));if(error)j.box.append(make('p',error));if(status==='inbox')j.box.append(make('p','Ouvrez TikTok → Boîte de réception sur votre téléphone pour terminer la publication.'));if(j.a.platform==='tiktok'&&text()&&(status==='inbox'||status==='published'))j.box.append(action('Copier le texte et les hashtags',async()=>{try{await navigator.clipboard.writeText(text());j.box.append(make('p','Texte copié. Collez-le dans TikTok.'));}catch{j.box.append(make('p','La copie est indisponible. Sélectionnez le texte dans le récapitulatif.'));}}));}
    form.onsubmit=async e=>{e.preventDefault();if(sending||step!==2)return;const error=validate();if(error){message.textContent=error;return;}if(!agree.checked){message.textContent='Cochez la confirmation après avoir vérifié votre contenu.';agree.focus();return;}sending=true;message.textContent='';previewBox.querySelector('video')?.pause();go(3);const chosen=selected();for(const input of form.querySelectorAll('input,select,textarea'))input.disabled=true;
      for(const a of chosen){const j={a,box:make('div','','ov-pub-result'),requestId:crypto.randomUUID()};jobs.push(j);statusList.append(j.box);show(j,'queued');}
      for(const j of jobs){try{const [kind,index]=media.value.split(':');const payload=j.a.platform==='tiktok'?{campaignId:campaign.id,accountId:j.a.id,requestId:j.requestId,confirm:true}:{campaignId:String(campaign.id),accountId:String(j.a.id),kind,imageIndex:Number(index||0),caption:text(),scheduledAt:when.value==='later'?new Date(date.value).toISOString():null,requestId:j.requestId};const r=await api(j.a.network,j.a.platform==='tiktok'?'uploads':'posts',{method:'POST',headers,body:JSON.stringify(payload)});j.id=(r.upload||r.post).id;j.scheduled=when.value==='later'&&j.a.platform!=='tiktok';show(j,(r.upload||r.post).status,(r.upload||r.post).error);if(j.scheduled)j.box.append(make('p','Publication programmée. Retrouvez son suivi dans Paramètres.'));}catch(err){show(j,'uncertain',err.message+' Vérifiez l’historique avant de renvoyer.');}}
      let busy=false;const started=Date.now();timer=setInterval(async()=>{if(!d.isConnected||Date.now()-started>10*60*1000){clearInterval(timer);return;}if(busy)return;busy=true;try{const pending=jobs.filter(j=>j.id&&!j.scheduled&&!['published','inbox','failed','cancelled'].includes(j.status));if(!pending.length){clearInterval(timer);return;}let meta=null;if(pending.some(j=>j.a.network==='meta')){try{meta=await api('meta','posts');}catch{for(const j of pending.filter(j=>j.a.network==='meta'))show(j,'uncertain','Suivi Meta indisponible. Vérifiez les résultats dans Paramètres.');}}for(const j of pending){if(j.a.network==='meta'&&!meta)continue;try{const r=j.a.network==='tiktok'?(await api('tiktok','uploads/'+j.id)).upload:meta.posts.find(p=>p.id===j.id);if(r)show(j,r.status,r.error);}catch{show(j,'uncertain','Suivi indisponible. Vérifiez les résultats dans Paramètres.');}}}catch{for(const j of jobs.filter(j=>j.a.network==='meta'&&j.id&&!['published','failed','cancelled'].includes(j.status)))show(j,'uncertain','Suivi indisponible. Vérifiez les résultats dans Paramètres.');}finally{busy=false;}},5000);
    };
    go(0);
  };
})();
